name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18.14.1"
    - name: Download source file
      run: wget https://raw.githubusercontent.com/rndquu/action-conventional-commits/master/src/main.ts
      shell: bash
    - name: Git clone conventional-commits repo
      run: git clone https://github.com/rndquu/action-conventional-commits
      shell: bash
    - name: Install dependencies
      run: yarn install
      shell: bash
    - name: Debug
      run: ls -la
      shell: bash
    - run: npx tsx action-conventional-commits/src/main.ts
      shell: bash
